package ar.edu.unlu.poker.modelo;

public enum Informe {

	SELECCIONAR_JUGADORES, CARTAS_REPARTIDAS, REALIZAR_APUESTAS, TIEMPO_DESCARTE, OBTENER_GANADOR, CANT_JUGADORES_INSUFICIENTES, 
	CANT_JUGADORES_EXCEDIDOS, JUGADOR_MANO, APUESTA_MAYOR, APUESTA_IGUAL, APUESTA_MENOR, DEVOLVER_GANADOR, FONDO_INSUFICIENTE
	
}
