package ar.edu.unlu.poker.modelo;

public enum Informe {

	SELECCIONAR_JUGADORES, CARTAS_REPARTIDAS, REALIZAR_APUESTAS, TIEMPO_DESCARTE, OBTENER_GANADOR, CANT_JUGADORES_INSUFICIENTES, 
	CANT_JUGADORES_EXCEDIDOS, JUGADOR_MANO, APUESTA_MAYOR, APUESTA_IGUAL, APUESTA_MENOR, DEVOLVER_GANADOR, FONDO_INSUFICIENTE, APUESTA_REALIZADA,
	JUGADOR_DECIDE_APOSTAR, APUESTA_INSUFICIENTE, JUGADOR_DECIDE_PASAR, TURNO_APUESTA_JUGADOR, FICHA_REALIZADA, RONDA_TURNO_TERMINADA, ENVITE_REALIZADO, PASAR_REALIZADO,
	MOSTRAR_MENU_APUESTAS, AVANCE_TURNO_APUESTA, INFORMAR_NO_TURNO_APUESTA
	
}
