package ar.edu.unlu.poker.modelo;

public enum Informe {
	JUGADOR_NUEVO_AGREGADO, CANT_JUGADORES_EXCEDIDOS, CANT_JUGADORES_INSUFICIENTES, ESTABLECER_NOMBRE_VENTANA_JUGADOR,
	JUGADOR_MANO, CARTAS_REPARTIDAS, TURNO_APUESTA_JUGADOR, APUESTA_REALIZADA, RONDA_APUESTAS_TERMINADA, TURNO_DESCARTE,
	FONDO_INSUFICIENTE, APUESTAS_DESIGUALES, DEVOLVER_GANADOR, JUGADOR_IGUALA_APUESTA, JUGADOR_PASA_APUESTA,
	SEGUNDA_RONDA_APUESTAS, CARTA_DESCARTADA, CARTA_YA_HABIA_SIDO_DESCARTADA, RONDA_APUESTAS_TERMINADA_SEGUNDA_RONDA,
	FONDO_INSUFICIENTE_SEGUNDA_RONDA, APUESTAS_DESIGUALES_SEGUNDA_RONDA, SE_AGREGAN_FONDOS, JUGADOR_SE_RETIRA,
	JUGADOR_SE_RETIRA_EN_PARTIDA, PARTIDA_COMENZADA, NOMBRE_REPETIDO, ID_ESTABLECIDO, LONGITUD_MAXIMA_ALCANZADA_FONDOS, FONDOS_INSUFICIENTES_COMENZAR_PARTIDA, APUESTA_INSUFICIENTE

}
