package ar.edu.unlu.poker.vista.consola;

public enum Estados {
	MENU_PRINCIPAL, MENU_APUESTAS, SOLICITAR_NOMBRE_JUGADOR, SOLICITAR_APUESTAS, SOLICITAR_DESCARTES, ESPERANDO_ENVITE, SOLICITAR_FONDO_JUGADOR, MENU_APUESTAS_DESIGUALES
}
