package ar.edu.unlu.poker.vista.consola;

public enum Estados {
	MENU_PRINCIPAL, MENU_APUESTAS, SOLICITAR_NOMBRE_JUGADOR, SOLICITAR_APUESTAS, SOLICITAR_DESCARTES, ESPERANDO_ENVITE, SOLICITAR_FONDO_JUGADOR, MENU_APUESTAS_DESIGUALES,
	MENU_OPCION_DESCARTES, MENU_SELECCION_DESCARTES, MENU_SEGUNDA_RONDA_APUESTAS, ESPERANDO_ENVITE_SEGUNDA_RONDA, MENU_NUEVA_RONDA, MENU_APUESTAS_DESIGUALES_SEGUNDA_RONDA
}
